### ISSUE TITLE
Need a note in install/get started guides about using QDK on Ubuntu

### ISSUE THREAD

**Issue by crazy4pi314** [MicrosoftDocs/quantum-docs#2] opened 2021-02-04 02:21 UTC
I was trying to do some demos on stream today where I wanted to start from a base Ubuntu distro and spin up to a working Q# console app. I started with [these docs](https://docs.microsoft.com/en-us/azure/quantum/install-command-line-qdk?tabs=tabid-vscodet ) and ran into an annoying bug. I had the following docker file:
```docker
ARG VARIANT="focal"
FROM mcr.microsoft.com/vscode/devcontainers/base:0-${VARIANT}
USER root
RUN wget https://packages.microsoft.com/config/ubuntu/20.10/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
RUN sudo dpkg -i packages-microsoft-prod.deb
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
   && apt-get -y install --no-install-recommends dotnet-sdk-3.1
``` 

from there I installed the project templates as instructed here: https://docs.microsoft.com/en-us/azure/quantum/install-command-line-qdk?tabs=tabid-vscode#to-configure-for-another-environment 

and tried to run just the template generated console app, and got the following error:
```
Unhandled exception: System.DllNotFoundException: Unable to load shared library 'Microsoft.Quantum.Simulator.Runtime.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libMicrosoft.Quantum.Simulator.Runtime.dll: cannot open shared object file: No such file or directory
   at Microsoft.Quantum.Simulation.Simulators.QuantumSimulator.Init()
   at Microsoft.Quantum.Simulation.Simulators.QuantumSimulator..ctor(Boolean throwOnReleasingQubitsNotInZeroState, Nullable`1 randomNumberGeneratorSeed, Boolean disableBorrowing)
   at Microsoft.Quantum.EntryPointDriver.Simulation`3.<>c.<Simulate>b__0_0()
   at Microsoft.Quantum.EntryPointDriver.Simulation`3.RunSimulator(IEntryPoint`2 entryPoint, ParseResult parseResult, Func`1 createSimulator)
   at Microsoft.Quantum.EntryPointDriver.Simulation`3.Simulate(DriverSettings settings, IEntryPoint`2 entryPoint, ParseResult parseResult, String simulator)
   at Microsoft.Quantum.EntryPointDriver.Driver`3.Simulate(ParseResult parseResult, String simulator)
   at System.CommandLine.Invocation.CommandHandler.GetResultCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__20_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass15_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass24_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__21_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__19_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__11_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass13_0.<<UseExceptionHandler>b__0>d.MoveNext()
   ```
   
I couldn't find any solutions online, except for something that sounded similar on this SE question: https://stackoverflow.com/questions/52428334/unable-to-load-dll-microsoft-quantum-simulator-runtime-dll-centos-7   
Once I installed `libgomp` it fixed everything but was really hard to sort that our when even the LD_DEBUG wasn't helpful. 
Most science/research/data science users will be using Linux with the QDK so I strongly feel this needs to be noted in the docs or find a way to propagate a more helpful error message...

**Comment by geduardo** [comment] 2021-02-08 20:01
Possible duplicate of https://github.com/MicrosoftDocs/quantum-docs/issues/2

**Comment by dime10** [comment] 2021-02-12 17:31
> Possible duplicate of #2

@geduardo you linked to this issue, which one you mean?

**Comment by geduardo** [comment] 2021-02-15 12:10
> > Possible duplicate of #2
> 
> @geduardo you linked to this issue, which one did you mean?

Ups, I meant #20

**Comment by dime10** [comment] 2021-02-17 00:23
Hi @crazy4pi314, thank you for bringing this up. I can confirm this issue on my side, at least when using docker images, as regular Ubuntu images already come with this dependency (libgomp1).

I'll look into resolving this issue.

**Closed** 2021-03-02 01:10 UTC
Labels: documentation
