### ISSUE TITLE
The step to running in VS code

### ISSUE THREAD

**Issue by i-run-knee** [MicrosoftDocs/quantum-docs#158] opened 2021-04-30 07:50 UTC
I found there was some gap in having everything up and running in VS code. 
1. Add step to change python interpreter to minicode : (ctrl + shift + p > search for python interpreter> pick miniconda3)
2. in the terminal in vs code go to the env directory and activate it.

Some steps like these might make setup in vs code easier. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4cc2a2b-76ba-f5a2-2eba-c2878d300fea
* Version Independent ID: 48a7a218-babc-7e50-5b4e-83c91144ea7c
* Content: [Develop with Q# and Python - Azure Quantum ](https://docs.microsoft.com/en-us/azure/quantum/install-python-qdk?tabs=tabid-conda)
* Content Source: [articles/install-python-qdk.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/install-python-qdk.md)
* Service: **azure-quantum**
* Sub-service: **qdk**
* GitHub Login: @Bradben
* Microsoft Alias: **v-benbra**

**Comment by SoniaLopezBravo** [comment] 2021-04-30 10:34
Hello @i-run-knee ! I agree with you, it is not obvious that in VS Code, first you need to set the environment that you have just created in step 3 in order to use the `qsharp` package. Thank you for your feedback, I will add a couple of lines to clarify that part.

**Comment by dime10** [comment] 2021-04-30 19:25
Thank you @i-run-knee for this feedback. To complete the instructions you refer to, it is not required to configure VS Code for Python, since the "first Q# program" example is intended to be run from the same "environment you created during installation" (e.g. the Anaconda Prompt). But I agree that there is currently several issues that make it harder to use VS Code with a conda setup, and it would be useful to include more information on this topic.

Step 1 you propose actually requires that the Python extension for VS Code be installed, which the instructions do not cover and I don't think we should assume. Additionally, for me this step didn't resolve the underlying problem described below.

It appears that conda environments do not immediately work with PowerShell. Newer conda versions provide the `conda init powershell` command to set up support for conda environments within PowerShell. However, by default this will trigger an error message for users until they set their execution policy to `RemoteSigned`. Since VS Code uses PowerShell as its default terminal, this provides a significant hurdle to the user.
An easy way to circumvent this problem is for the user to open a cmd terminal in VS Code instead from which the `conda activate qsharp-env` command should work straightforwardly.

@cgranade I saw you contributed to conda, do you know if this is still an accurate description of the issue? Is the best resolution to instruct users to change the execution policy?

**Comment by SoniaLopezBravo** [comment] 2021-05-03 11:38
@dime10 I agree with you in everything, this tutorial needs several improvements. Instructions don't require to have Python extension for VS Code, but they do require to install QDK, which in fact is not necessary and it may be confusing. Furthermore, instructions don't tell where to create and save `host.py` and `Operation.qs` files, so if you run `python host.py` from Anaconda Prompt you'll also get an error if the root path is not the same.  

I think the best way to address both PowerShell execution policy issue and activation of qsharp environment, may be to run the program from cmd terminal in VS Code, as I edited in PR #160. But let's discuss what is the best solution to the users, as they may use other IDE.

**Comment by cgranade** [comment] 2021-05-03 15:13
> It appears that conda environments do not immediately work with PowerShell.

That's right, yes. On Windows installations, conda provides a Start Menu item to launch a PowerShell instance configured for use with the `conda` command:

![image](https://user-images.githubusercontent.com/31516/116893033-5bbe7100-abe5-11eb-9d7c-b34d4230442d.png)

Running that allows using `conda` commands in that instance without making any other profile or configuration changes, but then that doesn't allow using `conda` from VS Code, Windows Terminal, or other contexts where PowerShell is embedded not via that Start Menu link.

> Newer conda versions provide the `conda init powershell` command to set up support for conda environments within PowerShell. However, by default this will trigger an error message for users until they set their execution policy to `RemoteSigned`.

Right, this is the default security behavior on Windows 10 unless the user is in Developer mode. Nearly any tool that touches the command line heavily on Windows will at some point need the execution policy set to `RemoteSigned`, and `conda` is no exception there.

As a side note, it may be worth having the `conda init powershell` command raise a warning when the execution policy is too restrictive to use `conda`, with actionable advice on how to resolve.

> Since VS Code uses PowerShell as its default terminal, this provides a significant hurdle to the user.

A slight correction, but PowerShell is the default across Windows (Windows Terminal, Win+X, VS Code, etc.) since about 2017, such that this isn't specific to VS Code. The problem is also specific to Windows, since PowerShell for macOS and Linux do not support execution policies, and thus do not raise the same error when using `conda` with PowerShell on those platforms.

> An easy way to circumvent this problem is for the user to open a cmd terminal in VS Code instead from which the `conda activate qsharp-env` command should work straightforwardly (with conda in their path).

I'd recommend against suggesting `cmd` to users, since that is not the default shell, and future development for Windows is focused on providing cross-platform shell support via PowerShell. As a side note, this is why the build scripts used for _contributing_ to the QDK are all in PowerShell, since that allows us to share one set of build scripts across platforms more easily.

> @cgranade I saw you contributed to conda, do you know if this is still an accurate description of the issue? Is the best resolution to instruct users to change the execution policy?

I believe that would be the best resolution, yes, esp. as `Set-ExecutionPolicy -Scope CurrentUser RemoteSigned` is required for nearly any development work within PowerShell — we're far from unique in requiring that. As above, I think we could also contribute an improvement to the conda/conda repo that provides more actionable advice that makes it easier for users to enable their PowerShell configuration for use with conda. As the original developer of the `conda init powershell` feature, I'm happy to look at making that contribution if you think it'd be helpful here.

**Comment by cgranade** [comment] 2021-05-03 15:18
(Apologies, hit the wrong button, did not intend to close the issue.)

**Comment by dime10** [comment] 2021-05-04 11:57
Thank you @cgranade for your detailed response, this is very helpful!

I would say as well that a message warning the user if they have the wrong execution policy and how to change it would be really helpful and reassuring when running the `conda init` command. The security error one gets otherwise on PowerShell startup can be intimidating.

**Comment by cgranade** [comment] 2021-05-06 14:15
@dime10 Sounds good! I've opened up an issue on `conda` at conda/conda#10654 requesting the feature; hopefully something of that form should help users onboard more easily.

**Closed** 2021-05-15 14:21 UTC
Labels: doc-enhancement
