### ISSUE TITLE
translation missing

### ISSUE THREAD

**Issue by KittyYeungQ** [MicrosoftDocs/quantum-docs#83] opened 2021-03-26 09:33 UTC
Before migration, our docs are automatically translated to other languages. For example, es-es/ locale used to have something in Spanish, but now it says "don't have version in this language, here's English".

**Comment by Bradben** [comment] 2021-03-26 18:32
Cory confirmed this was part of the repo migration. Final step is to add the localized repos to the English repo so they can sync.

**Comment by cjgronlund** [comment] 2021-03-26 23:43
@KittyYeungQ 
The repo hadn't been onboarded to localization. That should be done as of a couple days ago, as Sunny reached out to be to give loc access. 
@Bradben 
@SunnyDeng

**Comment by SunnyDeng** [comment] 2021-03-26 23:46
We still in the new repo onboarding process to loc pipeline due to HCS creation issue. That's why you don't see translation yet. The translation will be back soon after onboarding success.

**Comment by Bradben** [comment] 2021-04-14 16:47
@SunnyDeng - is there an ETA on when the next localization batch will run?

**Comment by SunnyDeng** [comment] 2021-04-14 17:11
@Bradben we target to release the loc version in May.

**Comment by cjgronlund** [comment] 2021-04-19 20:59
@bradben @KittyYeungQ @SunnyDeng 
Translation release slated for May. Closing as resolved.

**Closed by cjgronlund** 2021-04-19 20:59 UTC
Labels: doc-bug
