### ISSUE TITLE
"Q# libraries" tab/page in API toc

### ISSUE THREAD

**Issue by gillenhaalb** [MicrosoftDocs/quantum-docs#7] opened 2021-01-09 13:28 UTC
Pointed out during a Learn review, the index link of the Q# libraries API section 404s. Note also that the link to "Q# libraries" on the "API reference" index page also sends to a nonexistent xref (`microsoft.quantum.qsharplibintro`). These index pages are the topicHref's in the toc [here](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/main/api/toc.yml), and seen in the screengrab below.

I think in fixing the Q# libraries page we will need to add something akin to the [Q# libraries page in the User Guide](https://docs.microsoft.com/en-us/quantum/user-guide/libraries/), but then also add information about which namespaces belong to which library (as well as those which are partially defined between standard and domain-specific libs). The latter is definitely crucial for this page because the API toc is organized by namespace, and therefore without it we would be contributing to more confusion about namespaces/libraries.

![image](https://user-images.githubusercontent.com/47889725/104092591-3350e680-5285-11eb-9a4e-ceff05973156.png)

**Comment by geduardo** [comment] 2021-02-11 13:22
@cgranade @ricardo-espinoza now that we are updating the API pipeline it could be good timing to fix this issue since we are still getting that 404 error.

**Comment by Bradben** [comment] 2021-02-11 19:15
Can't we just move the Q# library index to the root folder so it doesn't get overwritten? I tried to submit a PR for that to quantum-api, but don't have the permissions.

**Comment by geduardo** [comment] 2021-02-12 14:03
The problem is we don't have the index file, I think. Maybe we can just remove it from the TOC? Is it needed?

**Comment by Bradben** [comment] 2021-02-12 17:42
I have a copy that I grabbed from a working branch in quantum-docs-pr.  It is standard to have some kind of overview/index at the top of any section - in this case, it doesn't have super-critical information, but it needs to be there.

**Comment by geduardo** [comment] 2021-02-19 02:39
This should be fixed by this PR: https://github.com/microsoft/qdk/pull/70

**Comment by Bradben** [comment] 2021-02-22 18:54
> This should be fixed by this PR: https://github.com/microsoft/qdk/pull/70

Will the fix recover the old file or do you need a copy?

**Comment by geduardo** [comment] 2021-02-22 20:40
I have no idea (i can't view the PR). Tagging @cgranade for clarity.

**Comment by Bradben** [comment] 2021-03-11 18:50
@cgranade - not sure where we're at in this process (can't view the PR), but here is a backup copy of the missing [index file](https://microsoft.sharepoint.com/:t:/t/QuantumDocs/EWI7_969nJFJhOc8pQJFTHoBoPG3heXohJESGzDBCQqpeg?e=ivMNBF).

**Comment by geduardo** [comment] 2021-03-23 23:40
This can be closed

**Closed by geduardo** 2021-03-23 23:40 UTC
Labels: bug, documentation
