### ISSUE TITLE
Hi, in the first Q# snippet of this page, I don't think that the qubit is released when the Hadamard gate is applied. 

### ISSUE THREAD

**Issue by vivienlonde** [MicrosoftDocs/quantum-docs#113] opened 2021-04-13 07:47 UTC
[Tapez vos commentaires ici]

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: efb42ceb-2ded-bda8-90b7-e7eba5d6bfff
* Version Independent ID: 4ed13811-8ad5-556c-af72-049400d14a5c
* Content: [Invalidated qubits use checker - Quantum Development Kit - Azure Quantum ](https://docs.microsoft.com/fr-fr/azure/quantum/user-guide/machines/qc-trace-simulator/invalidated-qubits-use-checker)
* Content Source: [articles/user-guide/machines/qc-trace-simulator/invalidated-qubits-use-checker.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/user-guide/machines/qc-trace-simulator/invalidated-qubits-use-checker.md)
* Service: **azure-quantum**
* Sub-service: **qsharp-guide**
* GitHub Login: @vadym-kl
* Microsoft Alias: **vadym**

**Comment by geduardo** [comment] 2021-04-13 09:38
Duplicate of #114

**Closed by geduardo** 2021-04-13 09:38 UTC
